/**
 * 示例荷兰语单词数据
 * A1 级别基础词汇
 */

import type { Word } from '../types';

export const sampleWords: Word[] = [
  {
    id: '1',
    dutch: 'hallo',
    chinese: '你好',
    pronunciation: '/ɦɑˈloː/',
    example: 'Hallo, hoe gaat het?',
    exampleTranslation: '你好，你好吗？',
    category: 'basics',
    level: 'A1',
  },
  {
    id: '2',
    dutch: 'dank je',
    chinese: '谢谢',
    pronunciation: '/dɑŋk jə/',
    example: 'Dank je wel voor je hulp.',
    exampleTranslation: '非常感谢你的帮助。',
    category: 'basics',
    level: 'A1',
  },
  {
    id: '3',
    dutch: 'goedemorgen',
    chinese: '早上好',
    pronunciation: '/ˌɣudəˈmɔrɣə(n)/',
    example: 'Goedemorgen! Slap je goed?',
    exampleTranslation: '早上好！你睡得好吗？',
    category: 'basics',
    level: 'A1',
  },
  {
    id: '4',
    dutch: 'dag',
    chinese: '再见',
    pronunciation: '/dɑx/',
    example: 'Dag! Tot morgen!',
    exampleTranslation: '再见！明天见！',
    category: 'basics',
    level: 'A1',
  },
  {
    id: '5',
    dutch: 'ja',
    chinese: '是',
    pronunciation: '/jaː/',
    example: 'Ja, dat klopt.',
    exampleTranslation: '是的，没错。',
    category: 'basics',
    level: 'A1',
  },
  {
    id: '6',
    dutch: 'nee',
    chinese: '不',
    pronunciation: '/neː/',
    example: 'Nee, ik wil niet.',
    exampleTranslation: '不，我不想。',
    category: 'basics',
    level: 'A1',
  },
  {
    id: '7',
    dutch: 'water',
    chinese: '水',
    pronunciation: '/ˈʋaːtər/',
    example: 'Mag ik een glas water?',
    exampleTranslation: '我可以要一杯水吗？',
    category: 'food',
    level: 'A1',
  },
  {
    id: '8',
    dutch: 'brood',
    chinese: '面包',
    pronunciation: '/broːt/',
    example: 'Ik eet elke ochtend brood.',
    exampleTranslation: '我每天早上吃面包。',
    category: 'food',
    level: 'A1',
  },
  {
    id: '9',
    dutch: 'koffie',
    chinese: '咖啡',
    pronunciation: '/ˈkɔfi/',
    example: 'Wil je een kopje koffie?',
    exampleTranslation: '你想要一杯咖啡吗？',
    category: 'food',
    level: 'A1',
  },
  {
    id: '10',
    dutch: 'thee',
    chinese: '茶',
    pronunciation: '/teː/',
    example: 'Ik drink graag groene thee.',
    exampleTranslation: '我喜欢喝绿茶。',
    category: 'food',
    level: 'A1',
  },
  {
    id: '11',
    dutch: 'een',
    chinese: '一',
    pronunciation: '/eːn/',
    example: 'Ik heb een hond.',
    exampleTranslation: '我有一只狗。',
    category: 'numbers',
    level: 'A1',
  },
  {
    id: '12',
    dutch: 'twee',
    chinese: '二',
    pronunciation: '/tʋeː/',
    example: 'Er zijn twee katten.',
    exampleTranslation: '有两只猫。',
    category: 'numbers',
    level: 'A1',
  },
  {
    id: '13',
    dutch: 'drie',
    chinese: '三',
    pronunciation: '/dri/',
    example: 'Ik heb drie kinderen.',
    exampleTranslation: '我有三个孩子。',
    category: 'numbers',
    level: 'A1',
  },
  {
    id: '14',
    dutch: 'rood',
    chinese: '红色',
    pronunciation: '/roːt/',
    example: 'De appel is rood.',
    exampleTranslation: '苹果是红色的。',
    category: 'colors',
    level: 'A1',
  },
  {
    id: '15',
    dutch: 'blauw',
    chinese: '蓝色',
    pronunciation: '/blɑu/',
    example: 'De lucht is blauw.',
    exampleTranslation: '天空是蓝色的。',
    category: 'colors',
    level: 'A1',
  },
  {
    id: '16',
    dutch: 'groen',
    chinese: '绿色',
    pronunciation: '/ɣrun/',
    example: 'Het gras is groen.',
    exampleTranslation: '草是绿色的。',
    category: 'colors',
    level: 'A1',
  },
  {
    id: '17',
    dutch: 'moeder',
    chinese: '母亲',
    pronunciation: '/ˈmudər/',
    example: 'Mijn moeder is lerares.',
    exampleTranslation: '我的母亲是老师。',
    category: 'family',
    level: 'A1',
  },
  {
    id: '18',
    dutch: 'vader',
    chinese: '父亲',
    pronunciation: '/ˈvaːdər/',
    example: 'Mijn vader werkt in een kantoor.',
    exampleTranslation: '我的父亲在办公室工作。',
    category: 'family',
    level: 'A1',
  },
  {
    id: '19',
    dutch: 'vandaag',
    chinese: '今天',
    pronunciation: '/vɑnˈdaːx/',
    example: 'Vandaag is het maandag.',
    exampleTranslation: '今天是星期一。',
    category: 'time',
    level: 'A1',
  },
  {
    id: '20',
    dutch: 'morgen',
    chinese: '明天',
    pronunciation: '/ˈmɔrɣə(n)/',
    example: 'Morgen ga ik naar school.',
    exampleTranslation: '明天我去学校。',
    category: 'time',
    level: 'A1',
  },
];
